version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://arfo8ynm6olw6vpn.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ws7a44bs27asklgs
      - SPRING_DATASOURCE_USERNAME=ia0wc0ah6hnmwatb
      - SPRING_DATASOURCE_PASSWORD=qvdevqd4ttf4l42s
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    container_name: football-score-api
